<Z><A>12:38 =FABLAB KARAS: WATZ: WIEDER MAL WAS NEUES ZUM TESTEN ,.) HTTPS://MATTERMOST.COM
<Z>Exception in thread IRC_Client:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/piTelex/txDevIRC.py", line 218, in thread_function
    data = str(data_raw, 'utf8').replace('\n', '').split('\r')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 133: invalid start byte


